### ISSUE TITLE
Main functions deleted?

### ISSUE THREAD

**Issue by teddygroves** [Midnighter/dependency-info#10]
#### Problem description

The file `info.py` was deleted in pr #7. As far as I can tell this means that depinfo currently doesn't provide functions `print_dependencies` or `show_versions`. Maybe the file was deleted by accident? If not then I guess the documentation should be updated.

#### Code Sample

Create a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve).

```python 
from depinfo import print_dependencies
```

```
ImportError                               Traceback (most recent call last)
Input In [15], in <cell line: 1>()
----> 1 from depinfo import print_dependencies

ImportError: cannot import name 'print_dependencies' from 'depinfo' (/Users/tedgro/Code/Maud/.venv/lib/python3.10/site-packages/depinfo/__init__.py)

```

### Context

Python version 3.10

depinfo version 2.0.0

**Comment by Midnighter** [comment]
Hi,

I released too early with documentation etc. not up-to-date. My apologies.

The main intended usage is now via the command line:

```
depinfo -h
```

but I'm thinking about bringing back the `print_dependencies` function.
