### ISSUE TITLE
The package version of the package investigating should be part of the report

### ISSUE THREAD

**Issue by matthiaskoenig** [Midnighter/dependency-info#14]
This package is mainly used in debugging or reporting issues. A key information in the context is the version of package installed. This information is currently not part of the report.
I.e., doing something as
 ```
depinfo pkdb_data
 ```
Does not include the version of the package, but results in 

```
Platform Information
--------------------
Linux   5.13.0-44-generic-x86_64
CPython                   3.10.4

Dependency Information
----------------------
biopython        1.79
black          22.3.0
bump2version    1.0.1
flake8          4.0.1
flake8-mypy    17.8.0
isort          5.10.1
mypy            0.961
numpy          1.22.4
openpyxl       3.0.10
pandas          1.4.2
pint           0.19.2
pip-tools       6.6.2
pkdb-data       1.0.0
pymetadata      0.3.1
pytest          7.1.2
pytest-cov      3.0.0
python-slugify  6.1.2
requests       2.27.1
rich           12.4.4
tox            3.25.0

Build Tools Information
-----------------------
pip        22.0.4
setuptools 62.2.0
wheel      0.37.1
```
There should be the following information on top
```
Package Information
--------------------
pkdb_data     1.0.0
```
E.g. if somebody reports an issue for cobrapy we are interested in the cobrapy version they are using.

**Comment by Midnighter** [comment]
Absolutely, my mistake for accidentally dropping that information.

**Comment by Midnighter** [comment]
I looked into this, the package is actually included but the name is normalized. It is under "Dependency Information"

```
pkdb-data       1.0.0
```

Do you think it should be moved under its own section?

**Comment by Midnighter** [comment]
@matthiaskoenig any thoughts on this? Otherwise I would just close the issue since it's essentially solved.

**Comment by matthiaskoenig** [comment]
I completely overlooked that.
I would prefer to have it under its own section at the top, this is the first debug information one normally looks at. I.e. is the latest version of the package of interest installed (or which version).

But if this is not easily done I am ok with the current solution.

**Comment by Midnighter** [comment]
Please try out the latest release 2.2.0. It should do what you wanted.

**Comment by matthiaskoenig** [comment]
Perfect. Thanks so much.
