### ISSUE TITLE
No name in setup.py

### ISSUE THREAD

**Issue by smoretti** [Midnighter/dependency-info#2]
Hi

is it expected to have no name="depinfo" in setup() in setup.py?

Installation with *python setup.py install* creates an **UNKNOWN-1.4.0-py2.7.egg-info** instead of **depinfo-1.4.0-py2.7.egg-info** I guess.

Also no **depinfo/** or **depinfo.py** created!

**Comment by Midnighter** [comment]
Hey, most of those options are set in the `setup.cfg`. What are your Python, pip, and setuptools versions?

**Comment by Midnighter** [comment]
Saw that you're probably running Python 2.7 so I tried with that and ran `python setup.py install`. For me it installs just fine. Here are the versions of my environment:

```
System Information
==================
OS                     Linux
OS-release 4.15.0-23-generic
Python             2.7.15rc1

Package Versions
================
depinfo     1.4.0
pbr         4.0.4
pip        10.0.1
pipdeptree 0.12.1
setuptools 39.2.0
wheel      0.31.1
```

You could also try to simply `pip install depinfo` or is there a specific reason why you want to install directly from source?

**Comment by smoretti** [comment]
We have a custom Python installation, not in standard places.
So it could come from that.

I managed to install depinfo properly with wheel file provided at Pypi.

Thanks
